### ISSUE TITLE
WIEN2k and WannSymm

### ISSUE THREAD

**Issue by shahramyalameha** [ccao/WannSymm#1]
Dear developers,
Is it possible to provide an example or tutorial for the Wien2k package? I did not reach an acceptable result...
Thank you,

Shahram

**Comment by rafaelgonzalezh** [comment]
Dear developers,
Could you please present an example to get the data of the original and symmetrized bands?
Best regards,
Rafael

**Comment by ccao** [comment]
Wien2Wannier uses "local axis" by default which is a feature currently under development. However, it is possible to circumvent this if you are able to redefine the local axis when Wien2wannier does the projection, so the Hamiltonian can be symmetrized.

**Comment by gxzhi** [comment]
> Dear developers, Could you please present an example to get the data of the original and symmetrized bands? Best regards, Rafael

In version 1.1.1, we add the function to derive band structure.
If "kpath" block is set, WannSymm will output two file:
  1. "bands_ori.dat" contains band struct derived by the original Hamiltonian
  2. "bands_symmed.dat" contains band struct derived by the symmetrized Hamiltonian

You can plot those files to compare the original band structure and the symmetrized one, with the command in gnuplot (for example)
```
 plot 'bands_ori.dat' w l, 'bands_symmed.dat' w l
```

An example of "kpath" block is showing below, where "nk_per_kpath" is the number of k-points per k-path.
``` 
nk_per_kpath = 101
begin kpath
G 0.000  0.000  0.000    X 0.500  0.000  0.000
X 0.500  0.000  0.000    M 0.500  0.500  0.000
M 0.500  0.500  0.000    G 0.000  0.000  0.000
end kpath
```

WannSymm v1.1.1 download link:
 https://github.com/ccao/WannSymm/archive/refs/tags/v1.1.1.tar.gz

We add an example that contains "kpath" block for calculating band structures.
https://github.com/ccao/WannSymm/tree/main/examples/04_SrVO3_t2g

**Comment by ccao** [comment]
The local axis has already been implemented. The detailed procedure for symmetrize Wien2k Hamiltonian is now in testing phase.
