### ISSUE TITLE
Symmetry induced hamiltonian generates incorrect band structure. 

### ISSUE THREAD

**Issue by rounoknaimniloy** [ccao/WannSymm#13]
In wannierization I keep num_iter=0, dis_num_iter=100. The hamiltonian, wannierization give can reproduce dft bands upto 1e-5 accuracy. But with symmetry hamiltonian the band structure degrades significantly. With no symmetry, fitted bands lie in the range -6 to 3.5eV. But with symmtery bands lie in the range -8 to 4.5. I have done dft & wannierization in QE using SOC. No symmetry hamiltonian wasn't well converged. DFT found two symmtery. Wannsymm found 4 as it takes the translational symmetry into consideration. Dft ignored translational symm because calculations were for 2d structre.  Guide me how I can symmetrized hamiltonian & reproduce dft bands accurately all well.

**Comment by ccao** [comment]
Please at least show some input/band structure results. Without more specific information, we cannot what is possibly going to wrong direction.
