### ISSUE TITLE
Symmetrize the Hamiltonian using magnetism but not SOC

### ISSUE THREAD

**Issue by LiuyichenYanwushang** [ccao/WannSymm#14]
I want to symmetrize a Hamiltonian that is magnetic but does not consider SOC. I want to know how to do it? Because SOC is not considered, wannier90_hr.dat is divided into up and down parts. I want to symmetrize them respectively. How should I set up my wannsymm.in? Can the author give an example?

**Comment by gxzhi** [comment]
Currently, for collinear magnetic calculations where hr.dat is divided into up(up_hr.dat) and down (dn_hr.dat) parts, we need some tricks to perform symmetrization with WannSymm: 

1. For FM: The up/down hr.dat can be symmetrized independently with "Global_TRsymm=F", "Spinors=F";

2. For AFM: The procedure is a little complex. Firstly merge up_hr.dat and dn_hr.dat to get a single full hr.dat. Then symmetrize the single full hr.dat. Finally divide the full hr.dat into up_hr.dat and dn_hr.dat again.

BTW, these tricks are only applicable to cases with the black&white or magnetic point groups, but not to spin space group. Spin space group may be supported in furture version.

**Comment by LiuyichenYanwushang** [comment]
I truly appreciate your assistance, thank you very much for your detailed explanation.
