### ISSUE TITLE
Impose symmetry

### ISSUE THREAD

**Issue by apezol** [ccao/WannSymm#3]
Hi, I was wondering if it is possible to impose some symmetry constraint in the input file. There's a flag apparently to do that which appears in the output, namely:

flag_symm_from_file         = False

If so, is there any template to do this?,

best regards,

**Comment by gxzhi** [comment]
Yes. If _Use_Symmetry= '${sym_input_file_name}'_ is contained in 'wannsymm.in' (main input file), WannSymm will use those symmetreis in '${sym_input_file_name}' for symmetrizing or calculating the characters/eigenvalues. 
 
The file '${sym_input_file_name}'  can be written in the same format as 'symmetries.dat' file which is one of WannSymm output files. And a  'symmetries.dat' can be directly used as a symmetry input file without any changes.


If we assume ${sym_input_file_name} is named 'symmetries.in', then add this line in 'wannsymm.in' file:
```
Use_Symmetry = 'symmetries.in'
```

A symmetry written in 'symmetries.in' contains 3 parts. 1) 3x3 rotation matrix, use the lattice vectors as basis; 2) translation vector; 3) a flag ( T or F ) indicating time-reversal operation.

An example of 'symmetries.in' reads (it contains 6 rotation and a time-reversal) :
```
global time-reversal symmetry = True
nsymm=6
--- 1 ---
 1  0  0
 0  1  0
 0  0  1
0.000000 0.000000 0.000000
--- 2 ---
-1  1  0
-1  0  0
 0  0 -1
0.000000 0.000000 0.000000
--- 3 ---
 0 -1  0
 1 -1  0
 0  0  1
0.000000 -0.000000 0.000000
--- 4 ---
 1  0  0
 0  1  0
 0  0 -1
0.000000 0.000000 0.000000
--- 5 ---
-1  1  0
-1  0  0
 0  0  1
0.000000 0.000000 0.000000
--- 6 ---
 0 -1  0
 1 -1  0
 0  0 -1
0.000000 -0.000000 0.000000
```

Here is another example of 'symmetries.in' ( two symmetries, one of which is identity, and the other is time-reversal plus rotation):
```
nsymm=2
--- 1 ---
 1  0  0
 0  1  0
 0  0  1
0.000000 0.000000 0.000000 F
--- 2 ---
 0 -1  0
 1 -1  0
 0  0 -1
0.000000 0.000000 0.000000 T
```

**Comment by apezol** [comment]
Thank you very much!, is this the only thing I need to include in the input?. I'm trying to obtain a Hamiltonian which respects the symmetries of the group P3m1, therefore my 'symmetries.in' file looks like this:

> nsymm=6
--- 1 ---
 1  0  0
 0  1  0
 0  0  1
0.000000 0.000000 0.000000 F
--- 2 ---
 0 -1  0
 1 -1  0
 0  0  1
0.000000 0.000000 0.000000 F
--- 3 ---
-1  1  0
-1  0  0
 0  0  1
0.000000  0.000000 0.000000 F
--- 4 ---
 0 -1  0
-1  0  0
 0  0  1
0.000000 0.000000 0.000000 F
--- 5 ---
-1  1  0
 0  1  0
 0  0  1
0.000000 0.000000 0.000000 F
--- 6 ---
 1  0  0
 1 -1  0
 0  0  1
0.000000 0.000000 0.000000 F

But they don't appear in the output. am I missing something else?.

**Comment by gxzhi** [comment]
> Thank you very much!, is this the only thing I need to include in the input?. I'm trying to obtain a Hamiltonian which respects the symmetries of the group P3m1, therefore my 'symmetries.in' file looks like this:
> 
> > nsymm=6
> > --- 1 ---
> > 1  0  0
> > 0  1  0
> > 0  0  1
> > 0.000000 0.000000 0.000000 F
> > --- 2 ---
> > 0 -1  0
> > 1 -1  0
> > 0  0  1
> > 0.000000 0.000000 0.000000 F
> > --- 3 ---
> > -1  1  0
> > -1  0  0
> > 0  0  1
> > 0.000000  0.000000 0.000000 F
> > --- 4 ---
> > 0 -1  0
> > -1  0  0
> > 0  0  1
> > 0.000000 0.000000 0.000000 F
> > --- 5 ---
> > -1  1  0
> > 0  1  0
> > 0  0  1
> > 0.000000 0.000000 0.000000 F
> > --- 6 ---
> > 1  0  0
> > 1 -1  0
> > 0  0  1
> > 0.000000 0.000000 0.000000 F
> 
> But they don't appear in the output. am I missing something else?.

Can you show me the "Symmetries' info" block in "wannsymm.out" file?

**Comment by apezol** [comment]
Yes, this is what I get:

Symmetries' info:
symm   1: Identity

**Comment by gxzhi** [comment]
> Yes, this is what I get:
> 
> Symmetries' info: symm 1: Identity

It seems that some error occured when the code is reading symmetries. To detect the origin of that error, I need more details. Is it convenient for you to show me the whole 'wannsymm.in' and 'wannsymm.out'?

And, I add an example showing the usage of 'Use_Symmetry' tag just a moment ago, I hope that example helpful.
https://github.com/ccao/WannSymm/tree/main/examples/05_K233_S3

**Comment by apezol** [comment]
Ok, I see. Here are attached both files.

[wannsymm.zip](https://github.com/ccao/WannSymm/files/7789990/wannsymm.zip)

Thanks, I'll make some tests with that template.

**Comment by gxzhi** [comment]
@apezol 
I think the issue is that the tolerance of finding axis and angle of a rotation is too strict in previous version of WannSymm code.
And wannsymm.x stoped with error.

To fix that issue, I push a new commit  (3d29170). Please try that via
```
git clone https://github.com/ccao/WannSymm.git
```
or this zip file contaning the source code of this commit
[Wannsymm-3d29170.zip](https://github.com/ccao/WannSymm/files/7790397/Wannsymm-3d29170.zip)

**Comment by apezol** [comment]
Hi @gxzhi , apparently the code crashes, although it only performs the identity transformation. Perhaps I should add at this point that I was trying to impose that constraint because the code doesn't give the correct system's symmetry (I assume that this is related to a threshold when finding the symmetries). Is there something like a threshold criterion to find the system's symmetry?. Tracing back the error it gives:

ERROR: can not find rotated rvec and site.
loc=(  -0.05239,  -0.00002,   0.62387) dis=(  -0.77140,  -0.38573,  -0.04949) dis_int=(   -1    0    0) dis_rem=(   0.22860,  -0.38573,  -0.04949)

**Comment by gxzhi** [comment]
There is a threshold for finding symmetries named 'symprec' defined in spglib: https://spglib.github.io/spglib/variable.html#symprec
According to spglib, the variable 'symprec' is the distance tolerance in Cartesian coordinates to find crystal symmetry.

However, currently, the value of 'symprec' is coded in WannSymm source code in 'readinput.c' file:
```
 365     *p2number_of_symm = spg_get_symmetry(irotations, translations, max_num_of_symm,
 366                                       lattice4spg, atom_positions, atom_types,
 367                                       number_of_atoms_total, 1E-5);
```
the 1E-5 is the value of 'symprec'.

I think I should add a tag in _wannsymm.in_ for setting the value of 'symprec' manually in next version of WannSymm. Before that, you may try if it will work for your case by changing the source code directly (e.g. change the 1E-5 to 1E-3).

And an advice. I think, before changing the value of 'symprec', you should check whether it will work when the crystal lattice is in very good symmetry condition, by a manually created crystal structure with the space group.

**Comment by apezol** [comment]
Hi, that was a good suggestion, actually I tried to do that but since the code only accepts fractional coordinates I was a lil lazy to obtain them. Now it seems that the code worked, but I need to do some other post processing tests to see what it gives. Anyway, thanks!
