### ISSUE TITLE
diffrent bandstructure

### ISSUE THREAD

**Issue by bushra-lab** [ccao/WannSymm#4]
Hi, I am using this code to get symmetrized hr file. It is running perfectly fine. I have added the symmetry manually. However, when I am plotting the band structure, original and symmetrized band structures are very different from each other. and are actually not acceptable. 

Attached is the band structure. What do you think is the parameter, that needs to change to get the required aband structure
<img width="637" alt="Screen Shot 2022-01-10 at 12 11 12 PM" src="https://user-images.githubusercontent.com/80626508/148808820-f74e12bf-aecf-43b2-8910-f1ba01713cd8.png">
?

**Comment by gxzhi** [comment]
If the symmtrized band structure are obviously different from the original one, some possible reasons are
1. the symmetry group used for symmetrization is not a subgroup of the crystal's space group, 
2. the centers of Wannier functions (WFs) do not locate at atomic positions of crystal,
3. the WFs are not atomic-orbital-like

you can check:
1. the crystal structure, magnetic structure and applied symmetry in inputfile as well as outputfile of WannSymm;  
2. and 3. the Wannier functions.
The minimization of the spreading of WFs may change the centers  and shape of WFs. For WFs derived by Wannier90 code, if the minimization precedure is turned off ( set num_iter=0 ), the derived WFs are  atomic-orbital-like and their centers are atomic positions of crystal in most cases.

If there is still error and if it is convenient for you to share the main input file, crystal information and output file, please let me debug.

**Comment by bushra-lab** [comment]
Thank you so much for your reply,
My calculation is to check for nodal lines in the material. I am using materials with 2 symmetry operations and 8 symmetry operations, for two different calculations.
What i am expecting is that after using the WannSymm code, the code should take both cases in the same high symmetry
direction. but this is not the case. However, I am using
1. i am using num_iter=20
2. I am confused about how much num_dis_itera should be? Using less dis_iteration gives me good matching between DFT and wannier90 bands, but it is poorly converged.

secondly, if we follow your paper about WannSymm it explains in example 3 that in case wannnier90 band structure is not following symmetry is not exactly as Bastructure from DFT calculations, then Wannsym will take care of Symmetry and will make hr file exactly as DFT, unfortunatley, this is not the case for me.

**Comment by gxzhi** [comment]
I think the wrong bandstructure mostly originated from the WFs' centers that is not located at atomic positions.

And the DFT code you use will affect the order of orbitals in Wannier90's output. If the order of orbitals is not considered correctly, it will also result in wrong bandstructure. What DFT code you are using? Is it VASP, QE or Wien2k? 

It is hard to tell exactly the reason from current information, please show more details.
