### ISSUE TITLE
symmetry_hr_total is diffrent from individual symmetr_hr1 and syymmetr_hr2

### ISSUE THREAD

**Issue by bushra-lab** [ccao/WannSymm#6]
Hi experts, I am trying to symmetrize orbital like hamiltonian from wannier90. After running the code, i got total hamiltonian which when i plotted with DFT band, it was not a good fit at some high symmetry points(fig attached). 
Since the unit cell has 2 symmetry operations, i plotted those symmetry1 and symmetry2 hamiltonian file with DFT and to my surprise, both symmetry1 and symmetry2 hamiltonian file was in good fit with DFT. 
I want to understand what happened then when they were combined together
<img width="635" alt="Screen Shot 2022-01-18 at 3 01 54 PM" src="https://user-images.githubusercontent.com/80626508/150034248-aa9f2ca6-9a32-42be-8308-3e1c20f5329e.png">
<img width="635" alt="Screen Shot 2022-01-18 at 3 14 54 PM" src="https://user-images.githubusercontent.com/80626508/150034260-d35efe6c-1525-4dc8-a68c-f19b14f09620.png">

Unfortunately, I am not able to attach the folder

**Comment by gxzhi** [comment]
The combination procedure is just average the Hams related to those symmetries.

If you added the symmetry manually, I suggest paying more attention to the time-reversal symmetry (TRS).
For magnetic cases, if the TRS is not treated correctly, the results will be wrong.
