### ISSUE TITLE
How to set MAGMOM tag for different magnetization angles theta and phi 

### ISSUE THREAD

**Issue by bushra-lab** [ccao/WannSymm#7]
Dear Experts,

I am doing calculations with a magnetic material at different magnetization directions on theta=0 and phi changing from 0,90,45,60,30.
As far i understand, 0,0 angles are describing MAGMOM tag in 0 0 1 direction and 0,90 is for MAGMOM direction 1 0 0.

How can I set the MAGMOM tag for other angles?

Any suggestion or help can solve my problem.

**Comment by ccao** [comment]
MAGMOM contains 3 numbers for each atom, which specifies mx, my and mz, i.e. the moment components in each direction. If your default global moment axis is rotated, you need to specify mx, my and mz in the original cartesian coordinates.

**Comment by bushra-lab** [comment]
Thank you very much for your reply.

For all other users, working outside VASP, I find the following link very helpful.
https://www.vasp.at/wiki/index.php/SAXIS
