### ISSUE TITLE
Hoping to support the wannier90 v2.x and newer

### ISSUE THREAD

**Issue by fyangtcmp** [ccao/WannSymm#8]
I notice that the order of M_s listed in output is 0 0 0 ... 1 1 1 ... 
It is the same as wannier90 v1.x, but is different from wannier90 v2.x and newer. The M_s order of newer version of wannier90 is 0 1 0 1 0 1 ... 
Considering that VASP no longer supports wannier90 v1.x since 6.2.0. Could you please add a tag to change the default setting of M_s order?

希望能够增加对新版wannier90的支持：

从输出信息来看，程序把POSCAR中的轨道加倍至自旋空间时，假定的投影子的自旋顺序是000...111...，即自旋up和自旋down分成两个区块。
但在wannier90 v2.x及以后的版本，输出的hr.dat中，投影子的自旋顺序，是按照010101..交错排列的。
通过外部自行编写的程序重写hr.dat的投影子顺序以后，运行WannSymm.x，得到了正确的对称化wannier函数。可见正确的自旋顺序在处理具有磁结构的wannier函数时，扮演着非常关键的作用。
考虑到VASP自6.2.0开始，已经仅支持对接编译wannier90 v2.x及更新版本，请问是否能够加入一个tag，以支持将WannSymm中默认的自旋顺序修改至与新版wannier90相同？

**Comment by danielkaplan137** [comment]
I can confirm that something is seriously wrong with VASP 6.3.2 compiled with Wannier 3.1.0

**Comment by ccao** [comment]
Please try if the correct result can be obtained with
DFT_code = 'QE'
in the input file?

**Comment by ccao** [comment]
Please try if the correct result can be obtained with
DFT_code = 'QE'
in the input file?

**Comment by danielkaplan137** [comment]
Thanks,
But I'm already working with DFT_code=QE because of the changed spin order.

What else can I do?

**Comment by ccao** [comment]
Please provide some more details about what kind of problem you are facing. The input files for both wannsymm and wannier90, as well as the output spreadings of wannier90 and output file of wannsymm would be minimum.

**Comment by fyangtcmp** [comment]
> I can confirm that something is seriously wrong with VASP 6.3.2 compiled with Wannier 3.1.0

I also found this problem in VASP 6.3.0. It seems that the Wannier functions can only be constructed by the SCDM algorithm. But the SCDM algorithm does not consider any symmetries. So now I am working with VASP 5.4.4 compiled with Wannier90 3.1.0

**Comment by danielkaplan137** [comment]
Here it is.
The spread is quite normal, and the unsymmetrized Hamiltonian fits the DFT
bands reasonably well.
The WannSymm output file marks everything as normal.
Thanks again

**Comment by danielkaplan137** [comment]
Did you compile VASP 6.3.x with Wannier, without COMMS=MPI? I'm trying this
now, maybe this is the issue?

**Comment by fyangtcmp** [comment]
The VASP wiki did mention that the wannier90 lib should be compiled without 'COMMS=MPI'. 
I have tried this before on VASP 6.3.0 and it still did not work. 
I have done several simple tests and the VASP 6.3.0 show better performance that VASP 5.4.4 only in rare cases.
So I think using the downgraded version of VASP just make sense.

**Comment by danielkaplan137** [comment]
Still, the question would be, what changed from version 1.2 to 2.x and 3.x
in the VASP2Wannier interface.
I think it would be interesting to resolve that question.

**Comment by ccao** [comment]
So the problem seems to be with VASP2Wannier interface rather than WannSymm code?

**Comment by fyangtcmp** [comment]
Yes, setting DFTcode = 'QE' has solved my problem. Could you add some additional words to the README, just like" 'VASP' for VASP5 and WIEN2k (wannier90 version 1.x), 'QE'   for Quantum ESPRESSO and VASP6 (wannier90 version 2.x and newer)". I hope this may reduce the confusions about the meaning of this tag.
And thank you for your WannSymm codes. It helps me a lot in my researches and it is user-friendly.
