### ISSUE TITLE
Number of orbitals from input

### ISSUE THREAD

**Issue by ipark008** [ccao/WannSymm#9]
Hello,

I am wondering how do I fix the problem with the number of orbitals from input. I tried to symmetrize the Hamiltonian of Pt with SOC. My projection is spd-like basis but WannSymm reads nothing. It simply gives error message as follows:

!!! ERROR: Number of wannier orbitals mismatch:
 norb in inputfile 0
 norb in hr.dat 18 

Can you please give me some suggestions on this?

Thanks,

**Comment by ccao** [comment]
We can't give any specific suggestions without input files. Please make sure that your POSCAR has the correct element name (has to be Pt in your case).

**Comment by ipark008** [comment]
I used Quantum Espresso to obtain the Hamiltonian. Do I still need to provide POSCAR?

**Comment by ccao** [comment]
The code requires structure information to determine the symmetry group. So, this information must be provided in either POSCAR or the input file.

**Comment by ccao** [comment]
The code requires structure information to determine the symmetry group. So, this information must be provided in either POSCAR or the input file.
